### ISSUE TITLE
Teensy 3.5 and 3.6 support

### ISSUE THREAD

**Issue by rparasram** [Koromix/ty#6]
The loader does not seem to recognize the new 3.6. Would you be able to support it with this great utility?

**Comment by Koromix** [comment]
The Teensy Loader in the Teensyduino 1.30 works with Teensy 3.5 and Teensy 3.6 boards.

TyQt supports them too in the dev builds: https://bintray.com/koromix/ty/ty#files (TyQt-0.7.5-210-g00e62b8 is the most recent at this time). These builds are just as stable as the released versions.

**Comment by Koromix** [comment]
The 0.8.0 release should work with the new Teensy models. I'm closing this bug.
